version: '3'

services:
  attack-api:
    container_name: attack-api
    restart: always
    build: ./flask_app
  
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - attack-api