version: '3'

services:
  attack-api:
    container_name: attack-api
    restart: always
    build:
      context: ./
      dockerfile: ./flask_app/Dockerfile
    environment:
        JWT_SECRET_KEY: ${JWT_SECRET_KEY}
  
  nginx:
    container_name: nginx
    restart: always
    build: 
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - attack-api