name: snyk
on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  dependencies-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: snyk/actions/setup@master
      - name: Install Python dependencies with Pip
        working-directory: ./flask_app
        run: pip3 install -r requirements.txt
      - name: Test dependencies with Snyk
        working-directory: ./flask_app
        run: |
          snyk test
        env:
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
      - name: Test code with Snyk
        working-directory: ./flask_app
        run: |
          snyk code test
        env:
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
      - name: Monitor dependencies for security issues with Snyk
        working-directory: ./flask_app
        run: |
          snyk monitor
        env:
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
