name: snyk
on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.10
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - uses: snyk/actions/setup@master
      - name: Test dependencies with snyk
        run: |
          snyk test
        env:
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
      - name: Monitor dependencies for security issues with snyk
        run: |
          snyk monitor
        env:
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
  code-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - uses: snyk/actions/setup@master
      - name: Test code with snyk
        run: |
          snyk code test
        env:
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
