name: snyk
on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      # - name: Python Poetry Action
      #   uses: abatilo/actions-poetry@v2.1.6
      - uses: snyk/actions/setup@master
      - name: Test dependencies with snyk
        run: |
          snyk test
        env:
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
      - name: Monitor dependencies for security issues with snyk
        run: |
          snyk monitor
        env:
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
  code-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - uses: snyk/actions/setup@master
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.1.6
      - name: Test code with snyk
        run: |
          snyk code test
        env:
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
